# Supported: GCC, CLANG, ICX, NVCC, HIP
TOOLCHAIN ?= GCC
ENABLE_OPENMP ?= false
ENABLE_LIKWID ?= false
ENABLE_ISPC ?= false
ENABLE_CUDA ?= false
ENABLE_HIP ?= false

#Feature options
SIMD ?= SSE
OPTIONS +=  -DARRAY_ALIGNMENT=64
OPTIONS +=  -DSIMD_NAME=\"$(SIMD)\"
OPTIONS +=  -DMAX_NUM_THREADS=32
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER

ifeq ($(SIMD), SSE)
OPTIONS +=  -DVECTORSIZE=4
endif
ifeq ($(SIMD), AVX)
OPTIONS +=  -DVECTORSIZE=8
endif
ifeq ($(SIMD), AVX512)
OPTIONS +=  -DVECTORSIZE=16
endif
ifeq ($(SIMD), NEON)
OPTIONS +=  -DVECTORSIZE=4
endif
